routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\QuoteController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');


//Site Setting
Route::resource('/site-setting', 'App\Http\Controllers\SiteSettingController', [
    'names' => ['index' => 'site_setting', 'store' => 'site_setting.store', 'edit' => 'site_setting.edit', 'update' => 'site_setting.update', 'destroy' => 'site_setting.destroy']
]);


Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
    Route::resource('contact', ContactController::class);
    Route::resource('companies', CompanyController::class);
    Route::resource('orders', OrderController::class);
    Route::resource('product', ProductController::class);
    Route::resource('quotes', QuoteController::class);
    Route::resource('email-template', \App\Http\Controllers\EmailTemplateController::class);

//Export PDF
Route::get('order/order_pdf', [OrderController::class, 'orderPDF'])->name('order_pdf');
Route::get('quote/quote_pdf', [QuoteController::class, 'quotePDF'])->name('quote_pdf');
Route::get('company/company_pdf', [CompanyController::class, 'companyPDF'])->name('company_pdf');
Route::get('contacts/contact_pdf', [ContactController::class, 'contactPDF'])->name('contact_pdf');
//Export CSV
Route::get('order/order_csv', [OrderController::class, 'orderCSV'])->name('order_csv');
Route::get('quote/quote_csv', [QuoteController::class, 'quoteCSV'])->name('quote_csv');
Route::get('company/company_csv', [CompanyController::class, 'companyCSV'])->name('company_csv');
Route::get('contacts/contact_csv', [ContactController::class, 'contactCSV'])->name('contact_csv');
//Mail Send
Route::get('sendbasicemail', [MailController::class, 'basic_email'])->name('sendbasicemail');
Route::get('sendhtmlemail', [MailController::class, 'html_email'])->name('sendhtmlemail');
Route::get('sendattachmentemail', [MailController::class, 'attachment_email'])->name('sendattachmentemail');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public $timestamps = true;
    
    protected $guarded = ['id'];
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use App\Models\Api\CommonModel;
use Carbon\Carbon;
use Validator;
use App\Models\Product;

class ProductController extends Controller
{
    /**
     * Function to Api of  add.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $validatedData = Validator::make($request->all(), [
            'product_name' => 'required',
            'product_size' => 'required',
            'quantity' => 'required|numeric',
            'vendor_price' => 'required|numeric',
            'product_price' => 'required|numeric',
            'artwork_name' => 'required',
        ]);

        if ($validatedData->fails()) {
            return Response::json([
                'status' => false,
                'messege' => $validatedData->messages()->all(),
                'data' => []
            ], 404);
        }
        if ($validatedData) {
            $product = Product::create($request->all());
            if (!$product) {
                return Response::json([
                    'status' => false,
                    'message' => 'Something went wrong |try Again',
                    'data' => []
                ], 404);
            } else {
                return Response::json([
                    'status' => true,
                    'message' => 'Product Added Successfully',
                    'data' => $product,
                ], 200);
            }
        }
    }
    public function product_search(Request $request)
    {
        $validatedData = Validator::make($request->all(), [
            'key' => 'required|alpha_dash|min:3',
        ]);
        if ($validatedData->fails()) {
            return Response::json([
                'status' => false,
                'messege' => $validatedData->messages()->all(),
                'data' => []
            ], 404);
        }
        if ($validatedData) {
            $product = CommonModel::getSearch($request->key)->all();
            if ($product != "") {
                $prod = [];
                for ($i = 0; $i < count($product); $i++) {
                    $d['id'] = @$product[$i]->id;
                    $d['product_name'] =   @$product[$i]->product_name;
                    $d['product_size'] =  @$product[$i]->product_size;
                    $d['quantity'] = @$product[$i]->quantity;
                    $d['product_option'] =  @$product[$i]->product_option;
                    $d['vendor_price'] =  @$product[$i]->vendor_price;
                    $d['product_price'] =  @$product[$i]->product_price;
                    $d['product_weight'] =  @$product[$i]->product_weight;
                    $d['product_days'] =  @$product[$i]->product_days;
                    $d['product_sku'] =  @$product[$i]->product_sku;
                    $d['artwork_name'] = @$product[$i]->artwork_name;
                    $d['product_image'] = @$product[$i]->product_image;
                    $d['status'] =  @$product[$i]->status;
                    $prod[] = $d;
                }
                $products = $prod;
            } else {
                $products = [];
            }
            $data['product'] = $products;
            return response()->json(['status' => true, 'message' => "Search Successfully", 'data' => $data]);
        }
    }
    public function show($id)
    {
        $product = Product::findorFail($id); //searches for the object in the database using its id and returns it.

        return response()->json([
            'data' => $product,
            'message' => 'Product get successfully',
        ], 200);
    }
    public function update(Request $request)
    {

        $input  = $request->all();
        $validatedData = Validator::make($request->all(), [
            'product_name' => 'required',
            'product_size' => 'required',
            'quantity' => 'required|numeric',
            'vendor_price' => 'required|numeric',
            'product_price' => 'required|numeric',
            //'artwork_name' => 'required',
            'status' => 'required',
        ]);
        if ($validatedData->fails()) {
            return Response::json([
                'status' => false,
                'messege' => $validatedData->messages()->all(),
                'data' => []
            ], 404);
        }
        if ($validatedData) {
            $product = Product::find($input['id']);


            $icon_file = '';
            if($request->hasFile('product_image')){

                $file   = $request->file('product_image');
                $ds     = public_path('uploads/product');
                if(!is_dir($ds)){
                    @mkdir($ds, 0777, true);
                }
                // Delete old file
                if(file_exists($ds.'/'.$product->product_image)){
                    @unlink($ds.'/'.$product->product_image);
                }
                $fileName   = date('Ymdhis').rand(1,999).'-product.'.$file->getClientOriginalExtension();
                $file->move($ds,$fileName);

                $input['product_image'] = 'uploads/product/'.$fileName;
            }else{
                unset($input['product_image']);
            }

            if (!$product->update($input)) {
                return Response::json([
                    'status'  => false,
                    'messege' => 'Something went wrong |try Again',
                    'data' => []
                ], 404);
            } else {
                return Response::json([
                    'status'  => true,
                    'messege' => 'Product Updated Successfully',
                    'data' => $product
                ], 200);
            }
        }
    }
    public function index(Request $request)
    {
        $contact = Product::orderBy('id', 'DESC')->paginate(15);
        if (count($contact) > 0) {
            return Response::json([
                'status' => true,
                'messege' => 'Products List found Successfully',
                'data' => $contact,
            ], 200);
        } else {
            return Response::json([
                'status' => false,
                'messege' => 'No Products found',
                'errorCode' => '404'
            ], 404);
        }
    }
    public function destroy(Request $request, $id)
    {
        if ($id > 0) {
            if (Product::find($id)->delete()) {
                return Response::json([
                    'Message' => '',
                    'data' => 'Data Deleted Successfully',
                ], 200);
            } else {
                return Response::json([
                    'messege' => 'Something went wrong |try Again',
                    'errorCode' => '404'
                ], 404);
            }
        } else {
            return Response::json([
                'messege' => 'No Product found',
                'errorCode' => '404'
            ], 404);
        }
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $productDetails = \App\Models\Product::where('id', $id)->first();
        return view('product.edit', array('productDetails' => $productDetails));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/product/add.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid" ng-controller="ProductController">
    <div class="row">
        <div class="card ">
            <div class="card-header card-header-rose card-header-text">
                <div class="card-text">
                    <h4 class="card-title">Add Product</h4>
                </div>
            </div>
            <div class="card-body ">
                <form id="add_product_form" ng-submit="addProduct()" accept-charset="multipart/form-data" method="post">
                    <div class="row">
                        <div class="col-sm-6 input-field">
                            <label>Product Name</label>
                            <div class="form-group">
                                <input id="product_name" class="form-control" name="product_name" required="true">
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Product Option</label>
                            <div class="form-group">
                                <select class="selectpicker" id="product_option" name="product_option" data-style="select-with-transition" title="Single Select" >
                                    <option value="Option1">Option1</option>
                                    <option value="option2"> option2</option>
                                  </select>
                            </div>
                            
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Product Size</label>
                            <div class="form-group">
                                <input id="product_size" class="form-control" name="product_size" required="true">
                            </div>
                        </div>
                
                        <div class="col-sm-6 input-field">
                            <label>Quantity</label>
                            <div class="form-group">
                                <input id="quantity" class="form-control" name="quantity" >
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Vendor Price</label>
                            <div class="form-group">
                                <input id="vendor_price" class="form-control" name="vendor_price" >
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Product Price </label>
                            <div class="form-group">
                                <input type="text" id="product_price" class="form-control" name="product_price" required="true">
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Product Weight</label>
                            <div class="form-group">
                                <input type="number" id="product_weight" class="form-control" name="product_weight" required="true">
                            </div>
                        </div>
                        
                        <div class="col-sm-6 input-field">
                            <label>Product Days</label>
                            <div class="form-group">
                                <input type="number" id="product_days" class="form-control" name="product_days" required="true">
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Product SKU</label>
                            <div class="form-group">
                                <input type="text" id="product_sku" class="form-control" name="product_sku" required="true">
                            </div>
                        </div>
                        <div class="col-sm-6 input-field">
                            <label>Artwork Name</label>
                            <div class="form-group">
                                <input type="text" id="product_days" class="form-control" name="product_days" required="true">
                            </div>
                        </div>
                        
                            <div class="col-md-6 col-sm-6">
                                <h4 class="title">Add Product Image</h4>    
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{ asset('admin/img/image_placeholder.jpg') }}" alt="Add Slider">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                        <span class="btn btn-rose btn-round btn-file">
                                            <span class="fileinput-new">Select image</span>
                                            <span class="fileinput-exists">Change</span>
                                            <input type="file" id="product_image" name="product_image" required="true">
                                        </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        
                    
                      
                       <div class="col-sm-6">
                            <label>Status </label>
                            <div class="form-group select-wizard">
                              <select class="selectpicker" id="status" name="status" data-style="select-with-transition" title="Single Select" >
                                <option value="1">Active </option>
                                <option value="0"> In Active</option>
                              </select>
                            </div>
                        </div>
                    </div>
               
             
                    <div class="row">
                        <div class="card-footer">
                            
                             <button class="btn btn-rose" type="submit" id="add_new_btn" name="action">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>     
    </div>
</div>
@endsection

@section('jsScript')
 <script>
    function setFormValidation(id) {
      $(id).validate({
        highlight: function(element) {
          $(element).closest('.form-group').removeClass('has-success').addClass('has-danger');
          $(element).closest('.form-check').removeClass('has-success').addClass('has-danger');
        },
        success: function(element) {
          $(element).closest('.form-group').removeClass('has-danger').addClass('has-success');
          $(element).closest('.form-check').removeClass('has-danger').addClass('has-success');
        },
        errorPlacement: function(error, element) {
          $(element).closest('.form-group').append(error);
        },
      });
    }

    $(document).ready(function() {
      setFormValidation('#add_slider_form');
      CKEDITOR.replace('description');
    });
  </script>
  <script src="{{ asset('admin/js/controller/ProductController.js') }}"></script>
 <script src="{{ asset('admin/js/ckeditor/ckeditor/ckeditor.js') }}"></script>
  <script>
        
    </script>
@endsection

resources/views/product/index.blade.php
@extends('admin.layouts.app') @section('content')
<style type="text/css">
    .img-container.icon_img {
        width: 50%;
    }

</style>
<div id="preloaders" class="preloader"></div>

<div class="container-fluid" ng-controller="ProductController">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">assignment</i>
                  </div>
                  <h4 class="card-title">Product List</h4>
                  <div class="col-md-2 pull-right">
                  <a class="btn bg-gradient-primary mb-0 mt-lg-auto w-100" href="{{ route('product.create') }}">Add Product</a>
                  </div>
                  <div class="col-md-2 pull-right">
                    <div class="input-group">
                     
                      <input type="text" class="form-control" placeholder="Search Here" ng-model='search'>
                    </div>
                 
                  </div>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table responsive-table mainTable"  ng-init="getproductList()">
                      <thead>
                        <tr>
                          {{-- <th>Icon</th> --}}
                          <th>Product Name</th>
                          <th>Quantity</th>
                          <th>Product Price </th>
                          <th class="text-right">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        
                        <tr ng-repeat="row in TemplateList | filter:search" ng-class="contacts.tr_class">
                            {{-- <td><div class="img-container icon_img">
                              <img height="100px" weight="100px" src="{{url('/uploads/icon/<@ row.icon @>')}}" alt="...">
                            </div>
                            </td> --}}
                            <td><@ row.product_name @></td>
                            <td><@ row.quantity @></td>
                            <td><@ row.product_price @></td>
                            <td class="td-actions text-right">
                            <a href="{{url('product/<@ row.id @>/edit')}}" type="button" rel="tooltip" class="btn btn-success">
                              <i class="material-icons">edit</i>
                            </a>
                           
                          </td>
                        </tr>
                       <tr ng-if="horscopeList.length==0"><td colspan="15">No Records Found.</td></tr>
                      </tbody>
                    </table>
                    <div class="pagination" ng-show="horscopeList">
                    <pagination total-items="totalItems" ng-model="currentPage" ng-change="pageContactChanged()" items-per-page="numPerPage" boundary-links="true" rotate="false" class="pagination-sm" max-size="maxSize"></pagination>
                </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

@section('jsScript')
<script>

(function($){

var preloader = $('.preloader');
setTimeout(function(){

preloader.remove();

}, 2000);

})(jQuery);
</script> 

<script src="{{ asset('admin/js/controller/ProductController.js') }}"></script>
  
@endsection