routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\QuoteController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');


//Site Setting
Route::resource('/site-setting', 'App\Http\Controllers\SiteSettingController', [
    'names' => ['index' => 'site_setting', 'store' => 'site_setting.store', 'edit' => 'site_setting.edit', 'update' => 'site_setting.update', 'destroy' => 'site_setting.destroy']
]);


Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
    Route::resource('contact', ContactController::class);
    Route::resource('companies', CompanyController::class);
    Route::resource('orders', OrderController::class);
    Route::resource('product', ProductController::class);
    Route::resource('quotes', QuoteController::class);
    Route::resource('email-template', \App\Http\Controllers\EmailTemplateController::class);

//Export PDF
Route::get('order/order_pdf', [OrderController::class, 'orderPDF'])->name('order_pdf');
Route::get('quote/quote_pdf', [QuoteController::class, 'quotePDF'])->name('quote_pdf');
Route::get('company/company_pdf', [CompanyController::class, 'companyPDF'])->name('company_pdf');
Route::get('contacts/contact_pdf', [ContactController::class, 'contactPDF'])->name('contact_pdf');
//Export CSV
Route::get('order/order_csv', [OrderController::class, 'orderCSV'])->name('order_csv');
Route::get('quote/quote_csv', [QuoteController::class, 'quoteCSV'])->name('quote_csv');
Route::get('company/company_csv', [CompanyController::class, 'companyCSV'])->name('company_csv');
Route::get('contacts/contact_csv', [ContactController::class, 'contactCSV'])->name('contact_csv');
//Mail Send
Route::get('sendbasicemail', [MailController::class, 'basic_email'])->name('sendbasicemail');
Route::get('sendhtmlemail', [MailController::class, 'html_email'])->name('sendhtmlemail');
Route::get('sendattachmentemail', [MailController::class, 'attachment_email'])->name('sendattachmentemail');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/includes/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
<!--{{ config('app.name', 'Laravel') }}-->
<title>OMS</title>

<!-- Scripts -->


<!-- Fonts -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link href="{{ asset('css/developer.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/material-dashboard.min.css?v=2.1.2') }}" rel="stylesheet" />

<!-- CSS Just for demo purpose, don't include it in your project -->
<link href="{{ asset('admin/demo/demo.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css">
<!-- script file for javascript -->
<script type="text/javascript" src="{{ asset('admin/js/jquery-3.2.1.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/jquery-ui.min.js') }}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.0/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.0/angular-animate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.0/angular-aria.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.0/angular-messages.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular-sanitize.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular-resource.min.js"></script>


<script src="{{ asset('admin/js/ui-bootstrap-tpls-0.12.0.js') }}"></script>
<script src="{{ asset('admin/js/controller/MainController.js') }}"></script>
<script src="{{ asset('admin/js/controller/MainController.js') }}"></script>

resources/views/admin/includes/header.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-minimize">
              <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:;">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            {{-- <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form> --}}
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="javascript:;">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              {{-- <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li> --}}
              <li class="nav-item dropdown">
                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                </div>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
              </li>
            </ul>
          </div>
        </div>
      </nav>

resources/views/admin/includes/js-constant-variable.blade.php
<script type="text/javascript">
  var base_url = "{{url('/')}}";
  var api_url = "{{url('/admin/api/v1')}}";
</script>

resources/views/admin/includes/sidebar.blade.php
    <div class="sidebar" data-color="rose" data-background-color="black" data-image="{{ asset('admin/img/sidebar-1.jpg') }}">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo"><a href="{{ url('home') }}" class="simple-text logo-mini">
        OM
        </a>
        <a href="{{ url('home') }}" class="simple-text logo-normal">
          O-Management
        </a></div>
      <div class="sidebar-wrapper">
        <div class="user">
          <div class="photo">
            <img src="{{ asset('admin/img/user.png') }}" />
            
          </div>
          <div class="user-info">
            <a data-toggle="collapse" href="#collapseExample" class="username">
              <span>
               {{Auth::user()->fname}}
                <!-- {{Auth::user()->name}} -->
                <b class="caret"></b>
              </span>
            </a>
             <div class="collapse" id="collapseExample">
              <ul class="nav">
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span class="sidebar-mini"> MP </span>
                    <span class="sidebar-normal"> My Profile </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span class="sidebar-mini"> EP </span>
                    <span class="sidebar-normal"> Edit Profile </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span class="sidebar-mini"> S </span>
                    <span class="sidebar-normal"> Settings </span>
                  </a>
                </li>
              </ul>
            </div> 
          </div>
        </div>
        <ul class="nav">
          <li class="nav-item {{ Request::segment(1) === 'home' ? 'active' : null }} ">
            <a class="nav-link" href="{{ url('home') }}">
              <i class="material-icons">dashboard</i>
              <p> Dashboard </p>
            </a>
          </li>
           {{-- <li class="nav-item ">
            <a class="nav-link" href="{{ url('/admin/product') }}"> 
              <i class="material-icons">accessibility</i>
              <p> Product </p>
            </a>
          </li> --}}
          <li class="nav-item 
          {{ Request::segment(1) === 'companies' ? 'active' : null }}
          {{ Request::segment(1) === 'contact' ? 'active' : null }}
          ">
            <a class="nav-link" data-toggle="collapse" href="#tablesExamples1">
              <i class="material-icons">accessibility</i>
              <p> Customers
                <b class="caret"></b>
              </p>
            </a>
            <div class="collapse 
            {{ Request::segment(1) === 'companies' ? 'show' : null }}
          {{ Request::segment(1) === 'contact' ? 'show' : null }}
            " id="tablesExamples1">
              <ul class="nav">
            
             
                <li class="nav-item 
                {{ Request::segment(1) === 'companies' ? 'active' : null }}
                ">
                  <a class="nav-link" href="{{route('companies.index')}}">
                    <span class="sidebar-mini"> CL</span>
                    <span class="sidebar-normal"> Company List  </span>
                  </a>
                </li>
                <li class="nav-item
                {{ Request::segment(1) === 'contact' ? 'active' : null }}
                ">
                  <a class="nav-link" href="{{route('contact.index')}}">
                    <span class="sidebar-mini"> CL </span>
                    <span class="sidebar-normal">Contact List</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item 
          {{ Request::segment(1) === 'product' ? 'active' : null }}
          {{ Request::segment(1) === 'quotes' ? 'active' : null }}
          {{ Request::segment(1) === 'orders' ? 'active' : null }}">
            <a class="nav-link" data-toggle="collapse" href="#tablesExamples">
              <i class="material-icons">grid_on</i>
              <p> Projects
                <b class="caret"></b>
              </p>
            </a>
            <div class="collapse 
            {{ Request::segment(1) === 'product' ? 'show' : null }}
          {{ Request::segment(1) === 'quotes' ? 'show' : null }}
          {{ Request::segment(1) === 'orders' ? 'show' : null }}
            " id="tablesExamples">
              <ul class="nav">
                <li class="nav-item 
                {{ Request::segment(1) === 'product' ? 'active' : null }}
                ">
                  <a class="nav-link" href="{{route('product.index')}}">
                    <span class="sidebar-mini"> PL </span>
                    <span class="sidebar-normal"> Product List </span>
                  </a>
                </li>
                <li class="nav-item 
                {{ Request::segment(1) === 'quotes' ? 'active' : null }}
                ">
                  <a class="nav-link" href="{{route('quotes.index')}}">
                    <span class="sidebar-mini"> QL </span>
                    <span class="sidebar-normal">Quote List </span>
                  </a>
                </li> 
                <li class="nav-item 
                {{ Request::segment(1) === 'orders' ? 'active' : null }}
                ">
                  <a class="nav-link" href="{{route('orders.index')}}">
                    <span class="sidebar-mini"> OL </span>
                    <span class="sidebar-normal"> Orders </span>
                  </a>
                </li>
         
                {{-- <li class="nav-item ">
                  <a class="nav-link" href="">
                    <span class="sidebar-mini"> OM</span>
                    <span class="sidebar-normal"> Order Manager</span>
                  </a>
                </li> --}}
              </ul>
            </div>
          </li>
          <li class="nav-item {{ Request::segment(1) === 'email-template' ? 'active' : null }}">
            <a class="nav-link" href="{{route('email-template.index')}}"> 
              <i class="material-icons">email</i>
              <p> Email Template</p>
            </a>
          </li>
          
          {{-- <li class="nav-item ">
            <a class="nav-link" href=""> 
              <i class="material-icons">accessibility</i>
              <p> Reports</p>
            </a>
          </li> --}}
          <li class="nav-item ">
            <a class="nav-link" href=""> 
              <i class="material-icons">add_ic_call</i>
              <p> Admin</p>
            </a>
          </li>
          
           <li class="nav-item ">
            <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"> 
              <i class="material-icons">login</i>
              <p> Logout </p>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
            </a>
          </li>
        </ul>
      </div>
    </div>